### ISSUE TITLE
Documentation not up-to-date

### ISSUE THREAD

**Issue by JKetelaar** [Parabot/Parabot-317-API-Minified#104]
Old dependencies and repositories are given in the README

**Comment by Fryslan** [comment]
`<repositories>
            <repository>
                <id>git-parabot</id>
                <name>Parabot's Git based repo</name>
                <url>https://maven.parabot.org/</url>
            </repository>
        </repositories>

        <dependencies>
            <dependency>
                <groupId>org.parabot</groupId>
                <artifactId>client</artifactId>
                <version>2.7</version>
            </dependency>
            <dependency>
                <groupId>org.parabot</groupId>
                <artifactId>317-api-minified</artifactId>
                <version>1.21.3</version>
            </dependency>
        </dependencies>`
