### ISSUE TITLE
depositAllExcept spam

### ISSUE THREAD

**Issue by EmmanuelTorres** [Parabot/Parabot-317-API-Minified#19]
https://github.com/Parabot/Parabot-317-API-Minified/blob/master/src/org/rev317/min/api/methods/Bank.java#L212

depositAllExcept in the Bank class spams packets and occasionally causes DCs. The reason for this is even though the ID is added to the ignored ArrayList, the while loop means every 50ms regardless of if it was added or not will try to deposit it until the inventory doesn't contain any more. It moves onto the next item and does the same thing.

**Comment by JKetelaar** [comment]
Fixed within commit e11e8ec.
