### ISSUE TITLE
distanceTo()

### ISSUE THREAD

**Issue by El-Maestro** [Parabot/Parabot-317-API-Minified#27]
If you have two tiles:
Tile A=new Tile(123,123,0);
Tile B= new Tile(123,123,1);

distanceTo() will return a value of '0' because it does not take into account that fact that the tiles are on two planes. This causes huge problems when walking through buildings with multiple floors.

**Comment by JKetelaar** [comment]
You can get the plane of the tile, use that in your checks too.
