### ISSUE TITLE
Banking Class for PKH isn't properly hooked? 

### ISSUE THREAD

**Issue by Kozs** [Parabot/Parabot-317-API-Minified#33]
System.out.println(Bank.getBankItemIDs());

It returns 'null' and it's set to return null when the Bank isn't open. So the interface must be incorrect for the isOpen method

**Comment by JKetelaar** [comment]
Thanks, we figured the ID of the interface is different on PKHonor. This will be fixed with the new system to load settings!

**Comment by JKetelaar** [comment]
@Fryslan Could you provide the correct ID?

**Comment by Fryslan** [comment]
23350

**Comment by JKetelaar** [comment]
This should have been fixed as of now, can you test so @Fryslan?

**Comment by JKetelaar** [comment]
This is solved!
