### ISSUE TITLE
Near Reality #getLevel

### ISSUE THREAD

**Issue by iEatApplez** [Parabot/Parabot-317-API-Minified#42]
Skill.SKILL.getLevel() and #getCurrentLevel() give me this error
http://prntscr.com/9n0xmk

Skill.SKILL.getRealLevel() returns the correct level.

**Comment by JKetelaar** [comment]
@Fryslan will pick this up, thanks for the report!

**Comment by CapslockRSPS** [comment]
#currentStats == NB
#currentExp == fC not sC

**Comment by JKetelaar** [comment]
@CapslockRSPS: This has been implemented. Please confirm if it works.

**Comment by JKetelaar** [comment]
@CapslockRSPS / @iEatApplez: This has been implemented. Please confirm if it works.
