### ISSUE TITLE
PkHonor Walkto

### ISSUE THREAD

**Issue by TheKushStyle** [Parabot/Parabot-317-API-Minified#43]
Walkto doesn't work.
The hook + parameters. :+1:

**Comment by Kozs** [comment]
WalkTo hasn't worked for PKH since the Vietnam war.

**Comment by CapslockRSPS** [comment]
Fryslan has a fix for it.
[](https://www.parabot.org/community/topic/15062-pkhonor-walking-fix/)

**NOTE:**_ Can be outdated_

**Comment by TheKushStyle** [comment]
i know but the fix needs parameters according to jk that's why i added it here.

**Comment by CapslockRSPS** [comment]
Yea I believe PKHonor uses an extra boolean in their parameters.

**Comment by CapslockRSPS** [comment]
Fixed with commit bc68037.

**Comment by JKetelaar** [comment]
Solved in pull request #54
