### ISSUE TITLE
Players.getMyPlayer().getLocation().getPlane() is returning 0 no matter what

### ISSUE THREAD

**Issue by Reportin** [Parabot/Parabot-317-API-Minified#61]

**Comment by JKetelaar** [comment]
Could you provide some more information on what's going wrong?
What location (X, Y, Z)?

What server does this happen to?

**Comment by Fryslan** [comment]
Its probably a wrong hook, what server does have this issue?

**Comment by JKetelaar** [comment]
Due to no response, this will be closed
