### ISSUE TITLE
Console Spam - OS-Scpae

### ISSUE THREAD

**Issue by lordgmage** [Parabot/Parabot-317-API-Minified#79]
`drop flag 6889 is -1051294242
huf len 58
drop flag 9244 is -1051294242
huf len 58
drop flag 861 is -1051294242
drop flag 1017 is -1051294242
drop flag 4091 is -1051294242
drop flag 12831 is -1051294242
drop flag 4093 is -1051294242`
This is when doing nothing.

**Comment by JKetelaar** [comment]
This is OS-Scape related, it also happens when you open the client from your command line, without Parabot.
